name: release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install Python build
      run: python3 -m pip install build --user
    - name: Build Python wheel and source tarball
      run: python3 -m build --sdist --wheel --outdir dist/
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist

  publish:
    name: Publish release to PyPi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/rawake/
    permissions:
      id-token: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist
    - name: Publish distribution 📦 to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
